### ISSUE TITLE
Crash while playing around with the sliders while rendering

### ISSUE THREAD

**Issue by leMaik** [aTom3333/chunky-bloom-plugin#1]
I think it was when I changed the _downsampling ratio_.

```
Unchecked exception in render manager.
java.lang.ArrayIndexOutOfBoundsException: 2187
	at dev.ferrand.chunky.bloom.BloomFilter.interpolatePixel(BloomFilter.java:112)
	at dev.ferrand.chunky.bloom.BloomFilter.processFrame(BloomFilter.java:87)
	at se.llbit.chunky.renderer.scene.Scene.postProcessFrame(Scene.java:2061)
	at se.llbit.chunky.renderer.scene.Scene.postProcessFrame(Scene.java:2067)
	at se.llbit.chunky.renderer.DefaultRenderManager.finalizeFrame(DefaultRenderManager.java:438)
	at se.llbit.chunky.renderer.DefaultRenderManager.lambda$new$6(DefaultRenderManager.java:215)
	at se.llbit.chunky.renderer.PathTracingRenderer.render(PathTracingRenderer.java:99)
	at se.llbit.chunky.renderer.DefaultRenderManager.run(DefaultRenderManager.java:298)
```

**Comment by jackjt8** [comment]
Confirmed. Downsampling ratio slider causes out of bounds exception when used while rendering.
